# Generated by Django 4.0.5 on 2022-06-22 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_commands_repetition'),
    ]

    operations = [
        migrations.DeleteModel(
            name='commands',
        ),
    ]
