# Generated by Django 4.0.5 on 2022-06-22 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commands',
            name='repetition',
            field=models.IntegerField(null=True),
        ),
    ]
