# Generated by Django 4.0.5 on 2022-06-22 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_commands_repetition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commands',
            name='gap',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='commands',
            name='repetition',
            field=models.IntegerField(default=1),
        ),
    ]
